-- Yapay zeka ile üretilen villa içeriklerini saklamak için tablo
CREATE TABLE IF NOT EXISTS public."VillaAIContent" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "villa_id" UUID NOT NULL REFERENCES public."Villa"(id) ON DELETE CASCADE,
    "content_type" TEXT NOT NULL CHECK (content_type IN ('seo_description', 'title_suggestion', 'full_description')),
    "content" TEXT NOT NULL,
    "model_used" TEXT NULL,
    "prompt_used" TEXT NULL,
    "generated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "metadata" JSONB NULL
);

-- İndeksler
CREATE INDEX IF NOT EXISTS idx_villa_ai_content_lookup 
ON public."VillaAIContent" (villa_id, content_type, generated_at DESC);

-- RLS Güvenliği
ALTER TABLE public."VillaAIContent" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Villa içeriklerine erişim politikası"
ON public."VillaAIContent"
FOR ALL
USING (auth.role() = 'service_role' OR auth.role() = 'authenticated');

-- Benzersiz kısıtlama (upsert için)
ALTER TABLE public."VillaAIContent"
ADD CONSTRAINT villa_ai_content_villa_id_content_type_unique 
UNIQUE (villa_id, content_type); 